# Use the Just the Docs theme (dark)
remote_theme: just-the-docs/just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: beadl
# Set page title
title: "BEADL"
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/BEADL_logo_inv.png"

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "BEADL Editor":
    - "https://beta.beadl.org"
  "Code on GitHub":
    - "https://github.com/BEADL"
  "Kepecs Lab":
    - "https://sites.wustl.edu/kepecslab/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2022 Michael Wulf, Washington University in St. Louis, Kepecs Lab. Theme: <a href=\"https://just-the-docs.github.io/just-the-docs/\" target=\"_blank\">Just the Docs</a>."